# _config.yml
plugins:
    - jekyll-remote-theme # add this line to the plugins list if you already have one
remote_theme: pages-themes/midnight@v0.2.0

# Site settings
title: Apollo Notes
description: Notes repository
